# Generated by Django 5.0.7 on 2024-07-26 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=20)),
                ('reg_number', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
                ('wash', models.IntegerField(default=0)),
                ('costumers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costumers.costumers')),
            ],
        ),
    ]
